export { Producto } from './producto.model'
export { Persona } from './persona.model'
export { Usuario, RespuestaLogin } from './usuario.model'
export { TipoDocumento } from './tipodocumento.model'
export {Cargo} from './cargo.model'
export {Clientes} from './clientes.model'
export {Sucursal} from './sucursal.model'
export {Rol} from './rol.model'
export{Estado} from './estado.model'
export{MetodoPago} from './metodopago.model'
export{TipoTela} from './tipotela.model'
export {TipoComprobante} from './tipocomprobante.model'
export{DetallePedido} from './detallepedido.model'
export{DetalleVenta} from './detalleventa.model'
export{DocEntrada} from './docentrada.model'
export{DocEntradaProducto} from './docentradaproducto.model'
export { DocSalida} from './docsalida.model'
export {DocSalidaProducto} from './docsalidaproducto.model'
export{Empleado} from './empleado.model'
export {EntradaDocumento} from './entradadocumento.model'
export {Kardex} from './kardex.model'
export {Pedidos} from './pedidos.model'
export {Proveedor} from './proveedor.model'
export{SalidaDocumento} from './salidadocumento.model'
export { UsuarioAcceso} from './usuarioacceso.model'
export { Venta} from './venta.model'