export { PersonaService } from './persona/persona.service'
export { UsuarioService } from './usuario/usuario.service'
export { ProductoService } from './producto/producto.service'
export { TipoDocumentoService } from './tipodocumento/tipodocumento.service'
export {CargoService} from './cargo/cargo.service'
export{ClientesService} from './clientes/clientes.service'
export{SucursalService} from './sucursal/sucursal.service'
export{RolService} from './rol/rol.service'
export{EstadoService} from './estado/estado.service'
export{MetodoPagoService} from './metodopago/metodopago.service'
export {TipoTelaService} from './tipotela/tipotela.service'
export {TipoComprobanteService} from './tipocomprobante/tipocomprobante.service'
export {DetallePedidoService} from './detallepedido/detallepedido.service'
export {DetalleVentaService} from './detalleventa/detalleventa.service'
export {DocEntradaService} from './docentrada/docentrada.service'
export {DocEntradaProductoService} from './docentradaproducto/docentradaproducto.service'
export {DocSalidaService} from './docsalida/docsalida.service'
export {DocSalidaProductoService} from './docsalidaproducto/docsalidaproducto.service'
export {EmpleadoService} from './empleado/empleado.service'
export {EntradaDocumentoService} from './entradadocumento/entradadocumento.service'
export {KardexService} from './kardex/kardex.service'
export {PedidosService} from './pedidos/pedidos.service'
export {ProveedorService} from './proveedor/proveedor.service'
export {SalidaDocumentoService} from './salidadocumento/salidadocumento.service'
export {UsuarioAccesoService} from './usuarioacceso/usuarioacceso.service'
export {VentaService} from './venta/venta.service'